pipeline {
    agent any
    tools{
        nodejs "18.1.0"
    }
	parameters {
    string(name: 'version', defaultValue: '', description: 'app version')
}

    stages {
        stage("npm-login-cli"){
        steps{
//           sh 'npm install -g npm-cli-login'
        sh 'npm -v'
        }
        }
        stage("build") {
            steps {
                echo "building.."
                   //sh 'npm install'
                   //sh 'npm run build'
				   sh 'docker build . -f build.dockerfile -t builder'
            }
        }
        stage('test') {
            steps {
             // sh 'npm test'
			  sh 'docker build . -f test.dockerfile -t tester'
            }
        }

         stage('deploy') {
            steps {
               echo 'deploying..'
                 
				  sh 'docker run --volume /var/jenkins_home/workspace/volumes:/finalBuild builder mv -n build /finalBuild '
				  echo 'building image..'
                    sh 'docker build . -f deploy.dockerfile -t deploy'
					sh 'docker run --volume /var/jenkins_home/workspace/volumes/build:/build -d -p 3000:80 deploy'
					sh 'docker stop $(docker ps -a -q)'
            }
        }
        stage('publish') {

		environment{
			login = credentials("NPM-USERNAME")
			password = credentials("NPM-PASSWORD")
			email = credentials("NPM-EMAIL")
			token = credentials("npm-token")
		}
            steps {
               echo "publishing.."
               //sh 'npm config set registry https://registry.npmjs.org/wiktor12v_nodejs:_auth=$token'
               //sh 'npm config set _auth $token'
                //sh 'export NPM_USERNAME=$login'
                //sh 'export NPM_EMAIL=$email'
                //sh 'export NPM_PASSWORD=$password'
                //sh 'npm adduser <<!$login $password $email!'
//                sh 'git config --global user.email $email'
//                sh 'git config --global user.name $login'
               //sh 'npm version "1.8.0"'
               //sh 'npm publish'
			   //to moja nieudana próba zrobienia publisha na registry  :(
			   echo '{params.version}'
			    sh 'docker build . -f publish.dockerfile -t publish'
				sh "docker run --volume /var/jenkins_home/workspace/volumes:/final publish mv archive.tar.xz /final"
				
				
			 echo ' done'

            }
        }
    }
}
